 * [[Wallpaper Prank]]
 * [[YOU GOT QUACKED!]]
 * [[Reverse Shell]]
 * [[Fork Bomb]]
 * [[Utilman Exploit]]
 * [[WiFi Backdoor]]
 * [[Non-Malicious Auto Defacer]]
 * [[Lock Your Computer Message]]
 * [[Ducky Downloader]]
 * [[Ducky Phisher]]
 * [[FTP Download / Upload]]
 * [[Restart Prank]]
 * [[Silly Mouse, Windows is for Kids]]
 * [[Windows Screen rotation hack]]
 * [[Powershell Wget + Execute]]
 * [[Create Wireless Network Association (AUTO CONNECT) PINEAPPLE]]
 * [[Retrieve SAM and SYSTEM from a live file system]]
 * [[Ugly Rolled Prank]]